---
title: "DBM scorpion analysis"
author: "Phil leftwich"
date: "30/01/2020"
output: html_document
---

```{r}
 library(tidyverse)
library(lme4)
 library(MuMIn)
 library(lmerTest)
 library(piecewiseSEM)
 library(multcomp)
 library(lsmeans)
library(multcompView)
 library(ggplot2)
library(ggforce)
library(ggsignif)
library(survival)
library(survminer)
library(ggpol)
library(patchwork)

###https://rpkgs.datanovia.com/survminer/survminer_cheatsheet.pdf

```

All the chi square data
```{r chi-square}
###pupae
Opiontet <- c(131, 133, 132, 135)
resopiontet=chisq.test(Opiontet, p=c(1/4, 1/4, 1/4, 1/4))
resopiontet

Opiofftet=c(152,157,138,122)
resopiofftet=chisq.test(Opiofftet, p=c(1/4, 1/4, 1/4, 1/4))
resopiofftet

###adult
adult_Opiontet=c(131,128,130,133)
resadult_Opiontet=chisq.test(adult_Opiontet, p=c(1/4, 1/4, 1/4, 1/4))
resadult_Opiontet

adult_Opiofftet=c(143,155,134,122)
resadult_Opiofftet=chisq.test(adult_Opiofftet, p=c(1/4, 1/4, 1/4, 1/4))
resadult_Opiofftet

###shaking adult

shakeadult_opiofftet=c(0,0,69,0)
resshakeadult_opiofftet=chisq.test(shakeadult_opiofftet, p=c(1/4, 1/4, 1/4, 1/4))
resshakeadult_opiofftet

shakeadult_opiontet=c(0,0,0,0) ###cannot analyse as all zero! 


###pupae
pupae_Hr5ontet=c(152,118,135,115)
respupae_Hr5ontet=chisq.test(pupae_Hr5ontet, p=c(1/4, 1/4, 1/4, 1/4))
respupae_Hr5ontet

pupae_Hr5offtet=c(244,288,266,268)
reshr5offtet=chisq.test(pupae_Hr5offtet, p=c(1/4, 1/4, 1/4, 1/4))
reshr5offtet

###adult
adult_Hr5ontet=c(143,115,119,109)
resadult_Hr5ontet=chisq.test(adult_Hr5ontet, p=c(1/4, 1/4, 1/4, 1/4))
resadult_Hr5ontet

adult_Hr5offtet=c(228,274,243,231)
resadult_Hr5offtet=chisq.test(adult_Hr5offtet, p=c(1/4, 1/4, 1/4, 1/4))
resadult_Hr5offtet

###shaking adult

shakeadult_Hr5offtet=c(0,0,182,0)
resshakeadult_Hr5offtet=chisq.test(shakeadult_Hr5offtet, p=c(1/4, 1/4, 1/4, 1/4))
resshakeadult_Hr5offtet

```

Graphs of Pupae, Adult and total shaking numbers
```{r}
data1=read.csv("../Data/chi_sq.csv")
data1$Treatment <- factor(data1$Treatment, levels =c("on-tet","off-tet"))
data1$Transgenes = factor(data1$Transgenes, levels=c("Green", "Red", "None", "Green+Red"))

hr5_data1=subset(data1,Line=="HR5/IE1")

pal1=c("#00A08A","#FF0000","#D3DDDC","#35274A")

p1=ggplot(hr5_data1, aes(fill=Transgenes, y=Pupae, x=Treatment))+
geom_bar(position="dodge", stat="identity")+
theme(text=element_text(size=12),legend.title = element_text(size = 12),legend.text = element_text(size=12))+theme(panel.grid.major=element_blank(), panel.grid.minor=element_blank(), panel.border=element_blank(), panel.background=element_blank())+
  ###add border edges
  theme(axis.line.x = element_line(color="black", size = 1),axis.line.y = element_line(color="black", size = 1))+
### make bar sit at zero and get more regular tick marks
 scale_y_continuous(expand = c(0,0), breaks=seq(0,400, 50)) +
    geom_text(aes(x=1, y=10.3, label=""), vjust=-1)+
  ###set ylim 
  coord_cartesian(ylim=c(0, 300))+
  ### change x axis
  labs(x="", y="Number of Pupae")+
  ###specify colours
  scale_fill_manual(values=pal1)+
  ###no legend
 theme(legend.position="none")
p1

p2=ggplot(hr5_data1, aes(fill=Transgenes, y=Adult, x=Treatment))+
geom_bar(position="dodge", stat="identity")+
  theme(text=element_text(size=12),legend.title = element_text(size = 12),legend.text = element_text(size=12))+theme(panel.grid.major=element_blank(), panel.grid.minor=element_blank(), panel.border=element_blank(), panel.background=element_blank())+
  ###add border edges
  theme(axis.line.x = element_line(color="black", size = 1),axis.line.y = element_line(color="black", size = 1))+
### make bar sit at zero and get more regular tick marks
 scale_y_continuous(expand = c(0,0), breaks=seq(0,400,400)) +
    geom_text(aes(x=1, y=10.3, label=""), vjust=-1)+
  ###set ylim 
  coord_cartesian(ylim=c(0, 300))+
  ### change x axis
  labs(x="", y="Number of Adults")+
  ###specify colours
  scale_fill_manual(values=pal1)+
  ###no legend
 theme(legend.position="none")

p3=ggplot(hr5_data1, aes(fill=Transgenes, y=Shaking, x=Treatment))+
geom_bar(position="dodge", stat="identity")+
  theme(text=element_text(size=12),legend.title = element_text(size = 12),legend.text = element_text(size=12))+theme(panel.grid.major=element_blank(), panel.grid.minor=element_blank(), panel.border=element_blank(), panel.background=element_blank())+
  ###add border edges
  theme(axis.line.x = element_line(color="black", size = 1),axis.line.y = element_line(color="black", size = 1))+
### make bar sit at zero and get more regular tick marks
 scale_y_continuous(expand = c(0,0), breaks=seq(0,400,400)) +
    geom_text(aes(x=1, y=10.3, label=""), vjust=-1)+
  ###set ylim 
  coord_cartesian(ylim=c(0, 300))+
  ### change x axis
  labs(x="", y="Number of Shaking Adults")+
  ###specify colours
  scale_fill_manual(values=pal1)
  ###no legend




###OPIE2
opi_data1=subset(data1,Line=="OP/IE2")


p4=ggplot(opi_data1, aes(fill=Transgenes, y=Pupae, x=Treatment))+
geom_bar(position="dodge", stat="identity")+
theme(text=element_text(size=12),legend.title = element_text(size = 12),legend.text = element_text(size=12))+theme(panel.grid.major=element_blank(), panel.grid.minor=element_blank(), panel.border=element_blank(), panel.background=element_blank())+
  ###add border edges
  theme(axis.line.x = element_line(color="black", size = 1),axis.line.y = element_line(color="black", size = 1))+
### make bar sit at zero and get more regular tick marks
 scale_y_continuous(expand = c(0,0), breaks=seq(0,400, 50)) +
    geom_text(aes(x=1, y=10.3, label=""), vjust=-1)+
  ###set ylim 
  coord_cartesian(ylim=c(0, 300))+
  ### change x axis
  labs(x="", y="Number of Pupae")+
  ###specify colours
  scale_fill_manual(values=pal1)+
  ###no legend
 theme(legend.position="none")


p5=ggplot(opi_data1, aes(fill=Transgenes, y=Adult, x=Treatment))+
geom_bar(position="dodge", stat="identity")+
  theme(text=element_text(size=12),legend.title = element_text(size = 12),legend.text = element_text(size=12))+theme(panel.grid.major=element_blank(), panel.grid.minor=element_blank(), panel.border=element_blank(), panel.background=element_blank())+
  ###add border edges
  theme(axis.line.x = element_line(color="black", size = 1),axis.line.y = element_line(color="black", size = 1))+
### make bar sit at zero and get more regular tick marks
 scale_y_continuous(expand = c(0,0), breaks=seq(0,400,400)) +
    geom_text(aes(x=1, y=10.3, label=""), vjust=-1)+
  ###set ylim 
  coord_cartesian(ylim=c(0, 300))+
  ### change x axis
  labs(x="", y="Number of Adults")+
  ###specify colours
  scale_fill_manual(values=pal1)+
  ###no legend
 theme(legend.position="none")

p6=ggplot(opi_data1, aes(fill=Transgenes, y=Shaking, x=Treatment))+
geom_bar(position="dodge", stat="identity")+
  theme(text=element_text(size=12),legend.title = element_text(size = 12),legend.text = element_text(size=12))+theme(panel.grid.major=element_blank(), panel.grid.minor=element_blank(), panel.border=element_blank(), panel.background=element_blank())+
  ###add border edges
  theme(axis.line.x = element_line(color="black", size = 1),axis.line.y = element_line(color="black", size = 1))+
### make bar sit at zero and get more regular tick marks
 scale_y_continuous(expand = c(0,0), breaks=seq(0,400,400)) +
    geom_text(aes(x=1, y=10.3, label=""), vjust=-1)+
  ###set ylim 
  coord_cartesian(ylim=c(0, 300))+
  ### change x axis
  labs(x="", y="Number of Shaking Adults")+
  ###specify colours
  scale_fill_manual(values=pal1)


###cowplot to arrange figures
library(cowplot)
Figure1=plot_grid(p1, p2, p3,p4,p5,p6, nrow=2, labels=c("A","B","C","D","E","F"))
Figure1
```


```{r}



### off tet double hets comparing the two promoters and sex differences 
### have not added all the Hr5 data for wt, Green and Red! 

data3=read.csv("../Data/Book2.csv")

str(data3)
data3$Line=as.factor(data3$Line)
data3$Fluorescence=as.factor(data3$Fluorescence)

#####
data3$Days.post.eclosion=(data3$Days.post.eclosion-1)
#### changed here as apparently day 0 was day in cage and day 1 was the first eclosion date, so evrything shifted down by 1 to accommodate, does not change any of the analyses. 

#### double hets only!
data3_double_only=subset(data3, Fluorescence=="Green+Red")

str(data3_double_only)


### basic survival fit
library(survival)
fit <- survfit(Surv(Days.post.eclosion,Shaking.effect)
 ~ Line+Sex, data = data3_double_only)


### survival plot - number of shaking events over time
###https://rpkgs.datanovia.com/survminer/reference/ggsurvplot.html
###strata lines


Figure3=ggsurvplot(fit, data = data3_double_only,
 pval = FALSE,tables.theme = clean_theme(),
 fun="event",
 risk.table = TRUE,
 linetype = c("strata"), 
 xlim=c(1,7),
 ylim=c(0,1),
 break.y.by=c(0.2),
 break.x.by=c(1),
 conf.int = FALSE,
 font.x=10,
 font.y=10,
 font.tickslab=10,
 
 xlab="Days post eclosion", ### change to time in days
 ylab="Cumulative proportion shaking",
risk.table.y.text = FALSE,###no text for risk table
 risk.table.title="Number not shaking",
legend.labs=c("Hr5/ie1>AaHIT Female", "Hr5/ie1>AaHIT Male","Op/ie2>AaHIT Female","Op/ie2>AaHIT Male"),
palette= "npg",
size=1,
font.legend=list(face="italic",size=8),
fontsize=3,
censor.shape=""
###Darjeeling 2
)+
   guides(color = guide_legend(nrow=2, keywidth = 2, keyheight = 1.8,override.aes = list(shape = NA)))


###Only works if remove risk.table.y.text=False
###Figure3$table <- Figure3table +theme(axis.text.y = element_text(hjust=0,margin = margin(b = 0.5),face="italic", size="16"))

Figure3

```

```{r}
### export as tiff file to manuscript size and dpi requirements
tiff("Figure3.tiff", height = 3.68, width = 6.7, units = 'in', 
     compression = "lzw", res = 1200)
Figure3
dev.off()

```  



  
```{r}
###cox's proportional hazards fit

fit1 <- coxph(Surv(Days.post.eclosion, Shaking.effect) ~ Line+Sex, data = data3_double_only)
summary(fit1)
### confidence interval cox's p hazards figure
ggforest(fit1)

#### look at Line+Sex or Line*Sex?

### works ok - residuals of coxph fit model
ggcoxdiagnostics(fit1,
                 type = "deviance",
                  ox.scale = "linear.predictions")

###how long were non-shakers kept? Can I extend x-axis?


ftest=cox.zph(fit1)
ftest

```

```{r}
###datasheet for Hr5 egg laying

egghatch=read.csv("../Data/egg_hatch.csv")
egghatch
str(egghatch)
egghatch$Eggs.hatched=(egghatch$Eggs.laid-egghatch$Eggs.unhatched)
hatchrate=cbind(egghatch$Eggs.hatched,egghatch$Eggs.unhatched)
Eggs.hatched=(egghatch$Eggs.laid-egghatch$Eggs.unhatched)

plot(Eggs.laid/Eggs.hatched~Treatment, egghatch)

###Line 15 of eggs laid vs. hatched there is a typo 12 eggs hatched only 11 laid. Remove this datapoint from all analysis as in error 

egghatch14  <- egghatch[-c(14),]
hatchrate=cbind(egghatch14$Eggs.hatched,egghatch14$Eggs.unhatched)

```

```{r}
###overdispersion residual deviance/df - should be close to 1 if good (0.8-1.2) 388/51 = overdispersed

mod1=glm(hatchrate~Treatment,data=egghatch14,quasibinomial)
summary(mod1)
rsquared(mod1)
plot(mod1)
```



```{r}

### eggs laid only - not sure if needed as ran the cibnd analysis above so somewhat repetitive. 

plot(Eggs.laid~Treatment, egghatch14)

mod2=glm(Eggs.laid~Treatment,data=egghatch14, family=quasipoisson)
summary(mod2)


egghatch$Treatment <- factor(egghatch$Treatment, levels =c("on-tet","off-tet"))

  
pal=c("#3B9AB2","#EBCC2A")

library(ggpol)
 
p8=ggplot(data=egghatch14, aes(x = Treatment, y = Eggs.laid, fill=Treatment))+     theme(legend.position="none")+theme(panel.grid.major=element_blank(), panel.grid.minor=element_blank(), panel.border=element_blank(), panel.background=element_blank())+geom_boxjitter(jitter.color=NA,jitter.shape=21, outlier.shape = NA)+theme(axis.text.x = element_text(angle = 60, hjust =1))+theme(axis.line.x = element_line(color="black", size = 1),axis.line.y = element_line(color="black", size = 1))+labs(y="Number of eggs laid\n", x="")+

scale_fill_manual(values=pal)

egghatch14$Prophatch <- egghatch14$Eggs.hatched/egghatch14$Eggs.laid ### generates three infinite values that need to be replaced with zeros

is.nan.data.frame <- function(x)
    do.call(cbind, lapply(x, is.nan)) ###function to find and replace is.nan

egghatch14$Prophatch[is.nan(egghatch14$Prophatch)] <- 0 ### replace nan with 0

p9=ggplot(data=egghatch14, aes(x = Treatment, y = Prophatch, fill=Treatment))+     theme(legend.position="none")+theme(panel.grid.major=element_blank(), panel.grid.minor=element_blank(), panel.border=element_blank(), panel.background=element_blank())+geom_boxjitter(jitter.color=NA,jitter.shape=21, outlier.shape = NA)+theme(axis.text.x = element_text(angle = 60, hjust =1))+theme(axis.line.x = element_line(color="black", size = 1),axis.line.y = element_line(color="black", size = 1))+labs(y="Proportion of eggs hatched\n", x="")+

scale_fill_manual(values=pal)
library(patchwork)
combine <- (p8|p9) ###using patchwork to easily arrange plots

```  

```{r}

ggsave ("Figure6test.tiff", plot=combine, dpi=1200, compression='lzw', units="in", width=3.5, height=3.5)

```


```{r}
longevity=read.csv("../Data/longevity.csv")
longevity
str(longevity)

lifespan <- survfit(Surv(Lifespan)~ Treatment+Sex, data = longevity)

### survival plot
Figure5=ggsurvplot(lifespan, data = longevity,
 pval = FALSE, tables.theme=clean_theme(),
 risk.table = TRUE,
 size = 1,
 linetype = c("strata"), 
 break.x.by=c(5),
 break.y.by=c(0.2),
 conf.int = FALSE,
 font.x=10,
 font.y=10,
 font.tickslab=10,
  risk.table.title="Number alive",
 xlab="Days post eclosion", ### change to time in days
 risk.table.y.text = FALSE, ###no text for risk table,
legend.labs=c("Female, Hr5/ie1>AaHIT, off-tet", "Male, Hr5/ie1>AaHIT, off-tet", "Female, Hr5/ie1>AaHIT, on-tet","Male, Hr5/ie1>AaHIT, on-tet"),
palette=c("#FF0000", "#00A08A", "#F2AD00","#5BBCD6"),
size=0.8,
font.legend=list(face="italic",size=8),
fontsize=3,
censor.shape="",

)+
     guides(color = guide_legend(nrow=2, keywidth = 2, keyheight = 1.8,override.aes = list(shape = NA)))
```

```{r}
###custom figure dimensions

tiff("Figure5.tiff", height = 3.68, width = 6.7, units = 'in', 
     compression = "lzw", res = 1200)
Figure5
dev.off()


```



```{r}

###cox's proportional hazards fit

CoxTreatment=factor(longevity$Treatment, levels=c("on-tet", "off-tet")) ###change order for intercept

lifespan1 <- coxph(Surv(Lifespan) ~ CoxTreatment+Sex, data = longevity)
summary(lifespan1)
extractAIC(lifespan1)

lifespan2 <- coxph(Surv(Lifespan) ~ Treatment*Sex, data = longevity)
summary(lifespan2)
extractAIC(lifespan2)

###AIC fits are barely different


### confidence interval cox's p hazards figure
ggforest(lifespan2)
### won't plot interaction term!!!! Might have to do it manually. 

library(jtools) ### estimates builder - but needs a lot of work to make it look nice! 
lifespan3 <- coxph(Surv(Lifespan) ~ CoxTreatment*Sex, data = longevity)

plot_summs(lifespan3)

library(dotwhisker)
library(broom)

 dwplot(list(lifespan1, lifespan2)) ### compare different model intercepts

### works ok - residuals of coxph fit model
ggcoxdiagnostics(lifespan2,
                 type = "deviance",
                  ox.scale = "linear.predictions")




```


```{r}
geom_data <- read_csv("../Data/GEOM_MEAN.csv")
geom_data <- na.omit(geom_data)

pal=c("#3B9AB2","#EBCC2A")

p <-geom_data %>%
  mutate(SAMPLE = fct_relevel(SAMPLE, 
            "L2","L4","Pupae","1 DPE","2 DPE","3 DPE","4 DPE")) %>%

  mutate(TET=fct_relevel(TET, "ON-TET","OFF-TET"))%>%
  
  filter(SAMPLE != "4 DPE", SAMPLE != "1 DPE") %>%

  ggplot(aes(x=SAMPLE, y=MEAN, fill=TET))+
  geom_bar(stat="identity", color="black", position=position_dodge())+
  geom_errorbar(aes(ymin=MEAN-CI, ymax=MEAN+CI), width=0.2, position=position_dodge(0.9))+

  theme(panel.grid.major=element_blank(), panel.grid.minor=element_blank(), panel.border=element_blank(), panel.background=element_blank())+
  theme(axis.line.x = element_line(color="black", size = 1),axis.line.y = element_line(color="black", size = 1))+
 scale_fill_manual(values=pal)+
  labs(y="NRQ (± 95% CI)", x="")+
    theme(axis.text.x = element_text(angle = 60, hjust =1))+
  annotate("text", size=2, label = "a", x = 0.75, y = 0.4)+
  annotate("text", size=2, label = "a", x = 1.22, y = 0.34)+
    annotate("text", size=2, label = "b", x = 1.75, y = 0.59)+
  annotate("text", size=2, label = "b", x = 2.22, y = 0.7)+
    annotate("text", size=2, label = "a", x = 2.75, y = 0.29)+
  annotate("text", size=2, label = "abc", x = 3.22, y = 0.72)+
          annotate("text", size=2, label = "ab", x = 3.75, y = 0.57)+
  annotate("text", size=2, label = "d", x = 4.22, y = 2)+
                annotate("text", size=2, label = "c", x = 4.75, y = 0.85)+
  annotate("text", size=2, label = "d", x = 5.22, y = 2.5)


```

```{r}
tiff("Figures/alternative_Figure5.tiff", height = 3.5, width = 3.5, units = 'in', 
     compression = "lzw", res = 1200)
p
dev.off()


```

